# Generated by Django 4.2 on 2023-09-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westaway', '0002_passwordentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='home',
            field=models.BooleanField(default=True),
        ),
    ]
